name: old_school
description: Add old-school terminals to your html documents.
version: 0.3.0
homepage: https://github.com/ram6ler/old_school

environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  web: ^1.1.0
